// <auto-generated />
using System;
using LojaVirtual.Infrastructure.Persistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LojaVirtual.Infrastructure.Migrations
{
    [DbContext(typeof(LojaVirtualContext))]
    [Migration("20260416221542_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("LojaVirtual.Domain.Entities.Categoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("ID");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("ATIVO");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CRIADO_EM")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("DescCategoria")
                        .HasColumnType("VARCHAR(1000)")
                        .HasColumnName("DESC_CATEGORIA");

                    b.Property<string>("NomeCategoria")
                        .IsRequired()
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("NOME_CATEGORIA");

                    b.HasKey("Id")
                        .HasName("PK_CATEGORIA_ID");

                    b.ToTable("TB_CATEGORIA", (string)null);
                });

            modelBuilder.Entity("LojaVirtual.Domain.Entities.CategoriaProduto", b =>
                {
                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("char(36)")
                        .HasColumnName("CATEGORIA_ID");

                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("char(36)")
                        .HasColumnName("PRODUTO_ID");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("ATIVO");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CRIADO_EM")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("ID");

                    b.HasKey("CategoriaId", "ProdutoId")
                        .HasName("PK_CATEGORIA_PRODUTO");

                    b.HasIndex("CategoriaId")
                        .HasDatabaseName("IX_CATEGORIA_PRODUTO_CATEGORIA");

                    b.HasIndex("ProdutoId")
                        .HasDatabaseName("IX_CATEGORIA_PRODUTO_PRODUTO");

                    b.ToTable("TB_CATEGORIA_PRODUTO", (string)null);
                });

            modelBuilder.Entity("LojaVirtual.Domain.Entities.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("ID");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("ATIVO");

                    b.Property<string>("CpfCliente")
                        .IsRequired()
                        .HasColumnType("VARCHAR(15)")
                        .HasColumnName("CPF_CLIENTE");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CRIADO_EM")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("NomeCliente")
                        .IsRequired()
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("NOME_CLIENTE");

                    b.Property<string>("TelefoneCliente")
                        .HasColumnType("VARCHAR(20)")
                        .HasColumnName("TELEFONE_CLIENTE");

                    b.HasKey("Id")
                        .HasName("PK_CLIENTE_ID");

                    b.HasIndex("CpfCliente")
                        .IsUnique()
                        .HasDatabaseName("IX_CLIENTE_CPF");

                    b.ToTable("TB_CLIENTE", (string)null);
                });

            modelBuilder.Entity("LojaVirtual.Domain.Entities.Estoque", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("ID");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("ATIVO");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CRIADO_EM")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<Guid>("LojaId")
                        .HasColumnType("char(36)")
                        .HasColumnName("LOJA_ID");

                    b.Property<int>("QntdEstoq")
                        .HasColumnType("INT")
                        .HasColumnName("QNTD_ESTOQ");

                    b.Property<DateTime?>("ValidadeEstoq")
                        .HasColumnType("DATE")
                        .HasColumnName("VALIDADE_ESTOQ");

                    b.HasKey("Id")
                        .HasName("PK_ESTOQUE_ID");

                    b.HasIndex("LojaId")
                        .HasDatabaseName("IX_ESTOQUE_LOJA");

                    b.ToTable("TB_ESTOQUE", (string)null);
                });

            modelBuilder.Entity("LojaVirtual.Domain.Entities.EstoqueProduto", b =>
                {
                    b.Property<Guid>("EstoqueId")
                        .HasColumnType("char(36)")
                        .HasColumnName("ESTOQUE_ID");

                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("char(36)")
                        .HasColumnName("PRODUTO_ID");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("ATIVO");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CRIADO_EM")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("ID");

                    b.HasKey("EstoqueId", "ProdutoId")
                        .HasName("PK_ESTOQUE_PRODUTO");

                    b.HasIndex("EstoqueId")
                        .HasDatabaseName("IX_ESTOQUE_PRODUTO_ESTOQUE");

                    b.HasIndex("ProdutoId")
                        .HasDatabaseName("IX_ESTOQUE_PRODUTO_PRODUTO");

                    b.ToTable("TB_ESTOQUE_PRODUTO", (string)null);
                });

            modelBuilder.Entity("LojaVirtual.Domain.Entities.Loja", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("ID");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("ATIVO");

                    b.Property<string>("CnpjLoja")
                        .IsRequired()
                        .HasColumnType("VARCHAR(18)")
                        .HasColumnName("CNPJ_LOJA");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CRIADO_EM")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("NomeLoja")
                        .IsRequired()
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("NOME_LOJA");

                    b.HasKey("Id")
                        .HasName("PK_LOJA_ID");

                    b.HasIndex("CnpjLoja")
                        .IsUnique()
                        .HasDatabaseName("IX_LOJA_CNPJ");

                    b.ToTable("TB_LOJA", (string)null);
                });

            modelBuilder.Entity("LojaVirtual.Domain.Entities.Produto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("ID");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("ATIVO");

                    b.Property<Guid?>("ClienteId")
                        .HasColumnType("char(36)")
                        .HasColumnName("CLIENTE_ID");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CRIADO_EM")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("NomeProd")
                        .IsRequired()
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("NOME_PROD");

                    b.Property<decimal>("PrecoProd")
                        .HasColumnType("DECIMAL(10,2)")
                        .HasColumnName("PRECO_PROD");

                    b.HasKey("Id")
                        .HasName("PK_PRODUTO_ID");

                    b.HasIndex("ClienteId")
                        .HasDatabaseName("IX_PRODUTO_CLIENTE");

                    b.ToTable("TB_PRODUTO", (string)null);
                });

            modelBuilder.Entity("LojaVirtual.Domain.Entities.CategoriaProduto", b =>
                {
                    b.HasOne("LojaVirtual.Domain.Entities.Categoria", null)
                        .WithMany("CategoriaProdutos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CATEGORIA_PRODUTO_CATEGORIA");

                    b.HasOne("LojaVirtual.Domain.Entities.Produto", null)
                        .WithMany("CategoriaProdutos")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CATEGORIA_PRODUTO_PRODUTO");
                });

            modelBuilder.Entity("LojaVirtual.Domain.Entities.Estoque", b =>
                {
                    b.HasOne("LojaVirtual.Domain.Entities.Loja", null)
                        .WithMany("Estoques")
                        .HasForeignKey("LojaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ESTOQUE_LOJA");
                });

            modelBuilder.Entity("LojaVirtual.Domain.Entities.EstoqueProduto", b =>
                {
                    b.HasOne("LojaVirtual.Domain.Entities.Estoque", null)
                        .WithMany("EstoqueProdutos")
                        .HasForeignKey("EstoqueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ESTOQUE_PRODUTO_ESTOQUE");

                    b.HasOne("LojaVirtual.Domain.Entities.Produto", null)
                        .WithMany("EstoqueProdutos")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ESTOQUE_PRODUTO_PRODUTO");
                });

            modelBuilder.Entity("LojaVirtual.Domain.Entities.Produto", b =>
                {
                    b.HasOne("LojaVirtual.Domain.Entities.Cliente", null)
                        .WithMany("Produtos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_PRODUTO_CLIENTE");
                });

            modelBuilder.Entity("LojaVirtual.Domain.Entities.Categoria", b =>
                {
                    b.Navigation("CategoriaProdutos");
                });

            modelBuilder.Entity("LojaVirtual.Domain.Entities.Cliente", b =>
                {
                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("LojaVirtual.Domain.Entities.Estoque", b =>
                {
                    b.Navigation("EstoqueProdutos");
                });

            modelBuilder.Entity("LojaVirtual.Domain.Entities.Loja", b =>
                {
                    b.Navigation("Estoques");
                });

            modelBuilder.Entity("LojaVirtual.Domain.Entities.Produto", b =>
                {
                    b.Navigation("CategoriaProdutos");

                    b.Navigation("EstoqueProdutos");
                });
#pragma warning restore 612, 618
        }
    }
}
